---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: ambassador
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    # diagnostics:
    #   enabled: false
    # defaults:
    #   httpmapping:
    #     remove_response_headers:
    #       - x-envoy-upstream-service-time
    #       - server
    server_name: hotstar_envoy
    lua_scripts: |
      function envoy_on_response(response_handle)
        response_handle:headers():remove("x-envoy-upstream-service-time")
        response_handle:headers():remove("server")
      end
