---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: auth-service-http-obj
  namespace: ambassador-test
spec:
  auth_service: 'auth-service-grpc.ambassador-test:8993'
  allowed_request_headers:
    - 'X-HS-UserToken'
    - 'x-passport'
  allowed_authorization_headers:
    - 'X-HS-UserToken'
    - 'x-passport'
