---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: domain-service
spec:
  prefix: /domain-service/
  service: domain-service
---
apiVersion: v1
kind: Service
metadata:
  name: domain-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: domain-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: domain-service
    spec:
      containers:
        - name: backend
          image: docker.io/asher4hs/upstream-server:latest
          ports:
            - name: http
              containerPort: 3000
