name: Build Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build HTTP container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: auth-service-http
          tags: |
            dizy/ambassador-test-auth-service-http:latest
            dizy/ambassador-test-auth-service-http:${{ github.sha }}

      - name: Build gRPC container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: auth-service-grpc
          tags: |
            dizy/ambassador-test-auth-service-grpc:latest
            dizy/ambassador-test-auth-service-grpc:${{ github.sha }}

      - name: Build domain service image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: domain-service
          tags: |
            dizy/ambassador-test-domain-service:latest
            dizy/ambassador-test-domain-service:${{ github.sha }}
